version: 2

builds:
  - main: ./cmd/moleport
    binary: moleport
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/ousiassllc/moleport/internal/cli.Version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "moleport_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: ousiassllc
    name: moleport
